### ISSUE TITLE
Use a obsolete github authentication method

### ISSUE THREAD

**Issue by ilaborie** [yoannfleurydev/GitHub-Notifications#3]
After authentication, Github send me an email:

```

On July 6th, 2020 at 06:15 (UTC) you used a password to access an endpoint through the GitHub API using GitHub%20Notifications/1 CFNetwork/1126 Darwin/19.5.0 (x86_64):

https://api.github.com/notifications

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.
```

**Comment by yoannfleurydev** [comment]
Thanks a lot, I have this email once a week using the GitHub module in my Polybar, I guess it didn't send me another email while testing the application, and I thought I was using the correct endpoint all this time :facepalm:

**Comment by yoannfleurydev** [comment]
Fixed in the new release https://github.com/yoannfleurydev/GitHub-Notifications/releases/tag/v1.0.1 
Again, thanks a lot 👍
